declare namespace NodeJS {
  interface ProcessEnv {
    // Client SDK
    NEXT_PUBLIC_FIREBASE_CLIENT_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_CLIENT_AUTH_DOMAIN: string;
    NEXT_PUBLIC_FIREBASE_CLIENT_PROJECT_ID: string;
    NEXT_PUBLIC_FIREBASE_CLIENT_STORAGE_BUCKET: string;
    NEXT_PUBLIC_FIREBASE_CLIENT_MESSAGING_SENDER_ID: string;
    NEXT_PUBLIC_FIREBASE_CLIENT_APP_ID: string;
  }
}
